import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.util.Properties

/**
 * Generates `app.muster.AppInfo` into a source directory added to `commonMain`,
 * so the version name shown in the app comes from `version.properties` once
 * rather than being duplicated per platform. See DECISIONS.md -> "Config via
 * a generated Kotlin file, not a plugin".
 */
abstract class GenerateAppInfo : DefaultTask() {

    @get:Input
    abstract val versionName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile.resolve("app/muster").apply { mkdirs() }
        dir.resolve("AppInfo.kt").writeText(
            """
            |// Generated by the generateAppInfo Gradle task. Do not edit.
            |package app.muster
            |
            |const val APP_VERSION = "${versionName.get()}"
            |
            """.trimMargin()
        )
    }
}

/**
 * Reads a value out of `version.properties`, the single file that holds
 * `VERSION_NAME` so a CI release job can bump it by rewriting one line,
 * without touching Gradle or the version catalog.
 */
fun versionSetting(
    providers: ProviderFactory,
    versionProperties: RegularFile,
    name: String
): Provider<String> =
    providers.fileContents(versionProperties).asText.map { text ->
        Properties().apply { load(text.reader()) }.getProperty(name)
    }

fun versionCode(versionName: String): Int {
    val parts = versionName.split(".").mapNotNull { it.toIntOrNull() }
    require(parts.size == 3 && parts.all { it in 0..999 }) {
        "VERSION_NAME must be x.y.z with each part 0..999, was $versionName"
    }
    return parts[0] * 1_000_000 + parts[1] * 1000 + parts[2]
}
