import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.provider.ProviderFactory
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.util.Properties

/**
 * Generates `app.muster.SupabaseConfig` into a source directory that is added to
 * `commonMain`, so the URL and publishable key reach all four targets as a plain
 * Kotlin object rather than being hardcoded.
 *
 * See CONTEXT.md -> "Decisions already closed" for why this is a generated file
 * rather than BuildConfig, expect/actual, or a third-party plugin.
 */
abstract class GenerateSupabaseConfig : DefaultTask() {

    @get:Input
    abstract val url: Property<String>

    @get:Input
    abstract val publishableKey: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val url = url.get()
        val key = publishableKey.get()
        require(url.isNotBlank() && key.isNotBlank()) {
            "SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY must be set in " +
                "local.properties or in the environment."
        }

        val dir = outputDir.get().asFile.resolve("app/muster").apply { mkdirs() }
        dir.resolve("SupabaseConfig.kt").writeText(
            """
            |// Generated by the generateSupabaseConfig Gradle task. Do not edit.
            |package app.muster
            |
            |internal object SupabaseConfig {
            |    const val URL = "${url.escapeForKotlin()}"
            |    const val PUBLISHABLE_KEY = "${key.escapeForKotlin()}"
            |}
            |
            """.trimMargin()
        )
    }

    private fun String.escapeForKotlin() =
        replace("\\", "\\\\").replace("\"", "\\\"")
}

/**
 * Resolves a build-time setting: environment variable first, then
 * `local.properties`, which is gitignored.
 *
 * Never fails at configuration time. A missing value resolves to the empty
 * string and surfaces as the task's own error message when it runs, so a plain
 * project sync does not break on an unconfigured machine.
 */
fun supabaseSetting(
    providers: ProviderFactory,
    localProperties: RegularFile,
    name: String,
): Provider<String> =
    providers.environmentVariable(name)
        .orElse(
            providers.fileContents(localProperties).asText.map { text ->
                Properties().apply { load(text.reader()) }.getProperty(name).orEmpty()
            }
        )
        .orElse("")
        .map { it.trim() }
